### ISSUE TITLE
Webp isn't generated if desired width is the same as the source width

### ISSUE THREAD

**Issue by jfurrow** [mapbox/appropriate-images#6]
It appears that specifying a `width` property for an image, which is the exact width of the source image, prevents the `webp` format from being generated.

Take a look at the script's output for these three images:
```
Saved difficulty-icon-advanced-88.png
Saved difficulty-icon-advanced-88.png
Saved difficulty-icon-intermediate-102.png
Saved difficulty-icon-intermediate-102.png
Saved difficulty-icon-intro-56.png
Saved difficulty-icon-intro-56.png
```

And after subtracting one pixel from each image's desired width:
```
Saved difficulty-icon-advanced-87.png
Saved difficulty-icon-advanced-87.webp
Saved difficulty-icon-intermediate-101.png
Saved difficulty-icon-intermediate-101.webp
Saved difficulty-icon-intro-55.png
Saved difficulty-icon-intro-55.webp
```

**Comment by davidtheclark** [comment]
![dunno](https://user-images.githubusercontent.com/628431/28898272-c7c8c9ba-7799-11e7-921d-264b45bfb85c.gif)

**Comment by jfurrow** [comment]
😞

**Comment by jfurrow** [comment]
This seems to be a case of corrupt or improperly formatted PNGs, as other PNGs are working as expected. Closing!
